name: Create Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Get previous and current APP_VERSION
              id: get_versions
              run: |
                  PREV_VERSION=$(git show HEAD~1:main.py | grep APP_VERSION | awk -F '"' '{print $2}')
                  CURRENT_VERSION=$(grep APP_VERSION main.py | awk -F '"' '{print $2}')
                  echo "prev=$PREV_VERSION" >> $GITHUB_ENV
                  echo "curr=$CURRENT_VERSION" >> $GITHUB_ENV

            - name: Validate APP_VERSION
              run: |
                  if [[ ! "$curr" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    echo "Invalid APP_VERSION format: $curr"
                    exit 1
                  fi

            - name: Check if APP_VERSION changed
              run: |
                  if [ "${{ env.prev }}" != "${{ env.curr }}" ]; then
                    echo "VERSION_CHANGED=true" >> $GITHUB_ENV
                  else
                    echo "VERSION_CHANGED=false" >> $GITHUB_ENV

            - name: Create GitHub Release
              if: env.VERSION_CHANGED == 'true'
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.curr }}
                  release_name: Release ${{ env.curr }}
                  draft: false
                  prerelease: false
