name: Build and Release

on:
    release:
        types:
            - published

permissions:
    contents: write # Ensure the token has write permissions to upload assets

jobs:
    build:
        runs-on: macos-latest

        steps:
            # Debug Step: Check if GITHUB_TOKEN is set
            - name: Check GITHUB_TOKEN
              run: |
                  if [ -z "$GITHUB_TOKEN" ]; then
                    echo "GITHUB_TOKEN is not set"
                    exit 1
                  else
                    echo "GITHUB_TOKEN is set"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # Step 1: Check out the code
            - name: Checkout code
              uses: actions/checkout@v2

            # Step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt

            # Step 4: Build the app
            - name: Build app
              run: python setup.py py2app

            # Step 5: Create the DMG file
            - name: Create DMG
              run: |
                  brew install create-dmg
                  rm -f dist/*.dmg  # Ensure the output file doesn't already exist
                  create-dmg --volname "Mac Menubar App" --window-size 600 400 --icon-size 100 --icon "Mac Menubar App.app" 200 200 --app-drop-link 400 200 "dist/Mac Menubar App.dmg" "dist/Mac Menubar App.app"

            # Step 6: Upload the release asset
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: dist/Mac Menubar App.dmg
                  asset_name: Mac_Menubar_App.dmg
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
